@BudgetAppApi_HostAddress = http://localhost:8080

### Register John Doe
POST {{BudgetAppApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Password123!",
  "firstName": "John",
  "lastName": "Doe",
  "confirmPassword": "Password123!"
}


### Register Jan Kowalski
POST {{BudgetAppApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "jan.kowalski@example.com",
  "password": "Password123!",
  "firstName": "Jan",
  "lastName": "Kowalski",
  "confirmPassword": "Password123!"
}


### Login John Doe
# @name login
POST {{BudgetAppApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Password123!"
}


### Login Jan Kowalski
# @name loginJan
POST {{BudgetAppApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@example.com",
  "password": "Password123!"
}


### Create a new budget for John Doe
POST {{BudgetAppApi_HostAddress}}/api/budgets
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "title": "John's Budget",
  "totalAmount": 1000.00,
  "startDate": "2024-01-01",
  "endDate": "2024-12-31"
}


### Create a new budget for Jan Kowalski
POST {{BudgetAppApi_HostAddress}}/api/budgets
Content-Type: application/json
Cookie: {{loginJan.response.headers.Set-Cookie}}

{
  "title": "Jan's Budget",
  "totalAmount": 2000.00,
  "startDate": "2024-01-01",
  "endDate": "2024-12-31"
}


### Create a new budget for Jan Kowalski
GET {{BudgetAppApi_HostAddress}}/api/budgets/admin/all


#### Get current user info
GET {{BudgetAppApi_HostAddress}}/api/auth/me
Cookie: AuthToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxYmJmMzIxZi05MTFjLTQ3YWQtYjhhOC05MDA5NjY1NzY5NDEiLCJlbWFpbCI6Imphbi5rb3dhbHNraUBleGFtcGxlLmNvbSIsInN1YiI6IjFiYmYzMjFmLTkxMWMtNDdhZC1iOGE4LTkwMDk2NjU3Njk0MSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjIwMDAwMDAwMDAsImlzcyI6IkJ1ZGdldEFwcCIsImF1ZCI6IkJ1ZGdldEFwcFVzZXJzIn0.5uyaStpn9GnAIvvajezqAVi3r3958KtDvNYWJXvG-6s


