# ETAP 1: Budowanie (używamy obrazu SDK)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# 1. Kopiujemy plik rozwiązania (widziałam na screenie, że masz nowoczesny BudgetApp.slnx)
COPY BudgetApp.slnx ./

# 2. AUTOMATYZACJA: Kopiujemy wszystkie pliki .csproj zachowując strukturę ich folderów
COPY ["BudgetApp.Api/BudgetApp.Api.csproj", "BudgetApp.Api/"]
COPY ["BudgetApp.Application/BudgetApp.Application.csproj", "BudgetApp.Application/"]
COPY ["BudgetApp.Domain/BudgetApp.Domain.csproj", "BudgetApp.Domain/"]
COPY ["BudgetApp.Infrastructure/BudgetApp.Infrastructure.csproj", "BudgetApp.Infrastructure/"]

ARG VITE_API_URL=http://localhost:8080/api/
ENV VITE_API_URL=$VITE_API_URL
# 3. Przywracamy pakiety dla całego rozwiązania
RUN dotnet restore "BudgetApp.Api/BudgetApp.Api.csproj"

# 4. Kopiujemy całą resztę kodu źródłowego
COPY . .

# 5. Budujemy wersję Release
RUN dotnet publish "BudgetApp.Api/BudgetApp.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

# ETAP 2: Uruchomienie (obraz Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .



EXPOSE 8080

ENTRYPOINT ["dotnet", "BudgetApp.Api.dll"]