# ETAP 1: Budowanie (Node.js)
FROM node:20-alpine AS build
WORKDIR /app

# Kopiujemy definicje zależności
COPY package*.json ./

# Instalujemy zależności
RUN npm install --legacy-peer-deps

# Kopiujemy kod źródłowy
COPY . .

# Budujemy aplikację (powstanie folder 'dist')
ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# ETAP 2: Serwowanie (Nginx)
FROM nginx:alpine

# Kopiujemy zbudowane pliki Reacta do folderu, z którego Nginx serwuje strony
COPY --from=build /app/dist /usr/share/nginx/html

# (Opcjonalnie) Jeśli masz customowy config Nginxa, odkomentuj linię niżej:
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Uruchamiamy Nginx w trybie pierwszoplanowym (żeby kontener nie zgasł)
CMD ["nginx", "-g", "daemon off;"]